name:                command-history
version:             0.1.0.0
github:              "mitchellvitez/command-history"
license:             BSD3
author:              "Mitchell Vitez"
maintainer:          "mitchell@vitez.me"
copyright:           "Mitchell Vitez"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mitchellvitez/command-history#readme>

dependencies:
- base >= 4.7 && < 5
- text
- hspec
- directory

library:
  source-dirs: src

# executables:
#   command-history-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - command-history

tests:
  command-history-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - command-history
